Document: ms-sys
Title: Debian ms-sys Manual
Author: <insert document author here>
Abstract: This manual describes what ms-sys is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/ms-sys/ms-sys.sgml.gz

Format: postscript
Files: /usr/share/doc/ms-sys/ms-sys.ps.gz

Format: text
Files: /usr/share/doc/ms-sys/ms-sys.text.gz

Format: HTML
Index: /usr/share/doc/ms-sys/html/index.html
Files: /usr/share/doc/ms-sys/html/*.html
